swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /transaction/{transactionId}:
      get:
        security:
          - Bearer: []
        tags:
         - User Transaction
        summary: Content of the month's transaction
        description: API for current month content transaction
        parameters:
         - in: header
           type: string
           name: Authorization
           description: Attach Bearer JWT token
           required: true
         - name: transactionId
           in: path
           required: true
           type: integer
           format: int64
           description: ID transaction
        produces:
          - application/json
        responses: 
          '200':
            description: Content Successfully
            schema:
              type: array
              items:
                $ref: '#/definitions/TransactionResponse'
          '401':
            description: Invalid Filds
          '404':
            description: Not Found
          '500':
            description: Internal Server Error
  /transaction/{transactionId}/{id}:
      get:
        security:
          - Bearer: []
        tags:
          - User Transaction
        summary: Additional transaction detail
        description: API detailing each transaction of the current month
        parameters:
         - in: header
           type: string
           name: Authorization
           description: Attach Bearer JWT token
           required: true
         - name: transactionId
           in: path
           required: true
           type: integer
           format: int64
           description: ID transaction
         - name: id
           in: path
           required: true
           type: integer
           format: int64
           description: ID transaction Detail
        produces: 
         - application/json
        responses:
          '200':
            description: Content Successfully
            schema:
              type: array
              items:
                $ref: '#/definitions/TransactionDetailResponse'
          '401':
            description: Invalid Filds
          '404':
            description: Not Found
          '500':
            description: Internal Server Error
      delete:
        security:
          - Bearer: []
        tags:
          - User Transaction
        summary: Delete transaction
        description: API for delete content transaction in the list
        parameters:
          - name: transactionId
            in: path
            required: true
            type: integer
            format: int64
            description: ID transaction
          - name: id
            in: path
            required: true
            type: integer
            format: int64
            description: ID transaction detail
        responses:
          '204':
            description: Delete successfully
          '404':
            description: Not found
          '500':
            description: Internal Server Error
  /transaction/{transactionId}/add:
      post:
        security:
          - Bearer: []
        tags:
          - User Transaction
        summary: Add Content Transaction
        description: API to add a transaction to our transaction list
        parameters:
         - in: header
           type: string
           name: Authorization
           description: Attach Bearer JWT token
           required: true
         - name: transactionId
           in: path
           required: true
           type: integer
           format: int64
           description: ID transaction
         - in: body
           name: body
           description: Content Payload
           schema:
            $ref: '#/definitions/TransactionAdd'
        produces:
          - application/json
        responses:
          '201':
            description: Content Add Successfully
          '400':
            description: Invalid Filds
          '500':
            description: Internal Server Error
  /transaction/{transactionId}/edit:
      put:
        security:
          - Bearer: []
        tags:
          - User Transaction
        summary: Edit Content Transaction
        description: API for updating a transaction
        parameters:
          - in: header
            type: string
            name: Authorization
            description: Attach Bearer JWT token
            required: true
          - name: transactionId
            in: path
            required: true
            type: integer
            format: int64
            description: ID transaction
          - in: body
            name: body
            description: Update transaction attributes
            required: true
            schema:
              $ref: '#/definitions/TransactionEdit'
        produces:
          - application/json
        responses:
          '200':
            description: Category transaction retrieved successfully
            schema:
              $ref: '#/definitions/CategoryEditResponse'
          '400':
            description: Invalid Fields
          '500':
            description: Internal Server Error
  /transaction/{transactionId}/{id}/addNote:
      post:
        security:
          - Bearer: []
        tags:
          - User Transaction
        summary: Add Note Transaction
        description: API for add note transaction
        parameters:
          - in: header
            type: string
            name: Authorization
            description: Attach Bearer JWT token
            required: true
          - name: transactionId
            in: path
            required: true
            type: integer
            format: int64
            description: ID transaction
          - name: id
            in: path
            required: true
            type: integer
            format: int64
            description: ID transaction Detail
          - in: body
            name: body
            description: Add note transaction
            required: true
            schema:
              $ref: '#/definitions/TansactionAddNote'
        produces:
          - application/json
        responses:
          '201':
            description: Content Add Successfully
          '400':
            description: Invalid Filds
          '500':
            description: Internal Server Error
  /transaction/{transactionId}/{id}/editNote:
      put:
        security:
          - Bearer: []
        tags:
          - User Transaction
        summary: Edit Note Transaction
        description: API for updating a note transaction
        parameters:
          - in: header
            type: string
            name: Authorization
            description: Attach Bearer JWT token
            required: true
          - name: transactionId
            in: path
            required: true
            type: integer
            format: int64
            description: ID transaction
          - name: id
            in: path
            required: true
            type: integer
            format: int64
            description: ID transaction Detail
          - in: body
            name: body
            description: Update note transaction attributes
            required: true
            schema:
              $ref: '#/definitions/TransactionNote'
        produces: 
          - application/json
        responses:
          '200':
            description: Note transaction retrieved successfully
            schema:
              $ref: '#/definitions/TransactionNoteReponse'
          '400':
            description: Invalid Fields
          '500':
            description: Internal Server Error
  /transaction/{transactionId}/{id}/{noteId}:
      delete:
        security:
          - Bearer: []
        tags:
          - User Transaction
        summary: Delete Note
        description: API for delete note in transaction
        parameters:
          - in: header
            type: string
            name: Authorization
            description: Attach Bearer JWT token
            required: true
          - name: transactionId
            in: path
            required: true
            type: integer
            format: int64
            description: ID transaction
          - name: id
            in: path
            required: true
            type: integer
            format: int64
            description: ID transaction Detail
          - name: noteId
            in: path
            required: true
            type: integer
            format: int64
            description: ID note in transaction
        responses:
          '204':
            description: Delete successfully
          '404':
            description: Not found
          '500':
            description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  TransactionAdd:
    properties:
      id:
        type: integer
      date:
        type: string
      description:
        type: string
      mount:
        type: string
      balance:
        type: string
      transactionType:
        type: string
      category:
        type: string
  TransactionEdit:
    type: object
    properties:
      id:
        type: number
      description:
        type: string
      type:
        type: string
      category:
        type: string
  TansactionAddNote:
    type: object
    properties:
      id:
        type: integer
      note:
        type: string
  TransactionNote:
    type: object
    properties:
      id:
        type: number
      note:
        type: string
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
  TransactionResponse:
    type: object
    properties:
        body:
          type: object
          properties:
            id:
              type: integer
            date:
              type: string
            description:
              type: string
            mount:
              type: string
            balance:
              type: string
  TransactionDetailResponse:
    type: object
    properties:
        body:
          type: object
          properties:
            id:
              type: integer
            transactionType:
              type: string
            category:
              type: string
            notes:
             type: array
             items:
              type: object
              properties:
                id:
                  type: integer
                content:
                  type: string
  CategoryEditResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
  TransactionNoteReponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          