swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Retrieve Profile Data
      description: API for fetching a user profile
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Edit User Profil
      description: API for updating a user profile
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /balances/{balanceId}:
      get:
        security:
          - Bearer: []
        tags:
         - User Transaction
        summary: Content of the month's balance
        description: API for current month content balance retrieved with scale ID
        parameters:
         - in: header
           type: string
           name: Authorization
           description: Attach Bearer JWT token
           required: true
         - name: balanceId
           in: path
           required: true
           type: integer
           format: int64
           description: ID balance
        produces:
          - application/json
        responses: 
          '200':
            description: Content Successfully
            schema:
              type: array
              items:
                $ref: '#/definitions/BalanceResponse'
          '401':
            description: Invalid Filds
          '404':
            description: Not Found
          '500':
            description: Internal Server Error
  /balances/{balanceId}/transaction:
      post:
        security:
          - Bearer: []
        tags:
          - User Transaction
        summary: Add Transaction in Balance
        description: API to add a transaction in a balance
        parameters:
         - in: header
           type: string
           name: Authorization
           description: Attach Bearer JWT token
           required: true
         - name: balanceId
           in: path
           required: true
           type: integer
           format: int64
           description: ID balance
         - in: body
           name: body
           description: Content Payload
           schema:
            $ref: '#/definitions/TransactionAdd'
        produces:
          - application/json
        responses:
          '201':
            description: Content Add Successfully
          '400':
            description: Invalid Filds
          '500':
            description: Internal Server Error
  /balances/{balanceId}/transactions/{transactionId}:
      get:
        security:
          - Bearer: []
        tags:
          - User Transaction
        summary: Additional transaction detail
        description: API to retrieve specific transaction information
        parameters:
         - in: header
           type: string
           name: Authorization
           description: Attach Bearer JWT token
           required: true
         - name: balanceId
           in: path
           required: true
           type: integer
           format: int64
           description: ID balance
         - name: transactionId
           in: path
           required: true
           type: integer
           format: int64
           description: ID information Detail
        produces: 
         - application/json
        responses:
          '200':
            description: Content Successfully
            schema:
                $ref: '#/definitions/TransactionDetailResponse'
          '401':
            description: Invalid Filds
          '404':
            description: Not Found
          '500':
            description: Internal Server Error
      delete:
        security:
          - Bearer: []
        tags:
          - User Transaction
        summary: Delete transaction
        description: API for delete transaction in the list
        parameters:
          - name: balanceId
            in: path
            required: true
            type: integer
            format: int64
            description: ID balance
          - name: transactionId
            in: path
            required: true
            type: integer
            format: int64
            description: ID information detail
        responses:
          '204':
            description: Delete successfully
          '404':
            description: Not found
          '500':
            description: Internal Server Error
      put:
        security:
          - Bearer: []
        tags:
          - User Transaction
        summary: Edit transaction in balance
        description: API for updating a transaction in balance
        parameters:
          - in: header
            type: string
            name: Authorization
            description: Attach Bearer JWT token
            required: true
          - name: balanceId
            in: path
            required: true
            type: integer
            format: int64
            description: ID balance
          - name: transactionId
            in: path
            required: true
            type: integer
            format: int64
            description: ID information
          - in: body
            name: body
            description: Update information attributes
            required: true
            schema:
              $ref: '#/definitions/InformationEdit'
        produces:
          - application/json
        responses:
          '200':
            description: Category information retrieved successfully
            schema:
              $ref: '#/definitions/CategoryEditResponse'
          '400':
            description: Invalid Fields
          '500':
            description: Internal Server Error
  /balances/{transactionId}/note:
      post:
        security:
          - Bearer: []
        tags:
          - User Transaction
        summary: Add Note in Transaction
        description: API for add note in transaction
        parameters:
          - in: header
            type: string
            name: Authorization
            description: Attach Bearer JWT token
            required: true
          - name: transactionId
            in: path
            required: true
            type: integer
            format: int64
            description: ID transaction
          - in: body
            name: body
            description: Add note transaction
            required: true
            schema:
              $ref: '#/definitions/TansactionAddNote'
        produces:
          - application/json
        responses:
          '201':
            description: Content Add Successfully
          '400':
            description: Invalid Filds
          '500':
            description: Internal Server Error
  /balances/{transactionId}/notes/{noteId}:
      put:
        security:
          - Bearer: []
        tags:
          - User Transaction
        summary: Edit Note in Transaction
        description: API for updating a note in transaction
        parameters:
          - in: header
            type: string
            name: Authorization
            description: Attach Bearer JWT token
            required: true
          - name: transactionId
            in: path
            required: true
            type: integer
            format: int64
            description: ID transaction
          - name: noteId
            in: path
            required: true
            type: integer
            format: int64
            description: ID note
          - in: body
            name: body
            description: Update note transaction attributes
            required: true
            schema:
              $ref: '#/definitions/TransactionNote'
        produces: 
          - application/json
        responses:
          '200':
            description: Note transaction retrieved successfully
            schema:
              $ref: '#/definitions/TransactionNoteReponse'
          '400':
            description: Invalid Fields
          '500':
            description: Internal Server Error
      delete:
        security:
          - Bearer: []
        tags:
          - User Transaction
        summary: Delete Note in Transaction
        description: API for delete note in transaction
        parameters:
          - in: header
            type: string
            name: Authorization
            description: Attach Bearer JWT token
            required: true
          - name: transactionId
            in: path
            required: true
            type: integer
            format: int64
            description: ID transaction
          - name: noteId
            in: path
            required: true
            type: integer
            format: int64
            description: ID note
        responses:
          '204':
            description: Delete successfully
          '404':
            description: Not found
          '500':
            description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  TransactionAdd:
    properties:
      date:
        type: string
      description:
        type: string
      mount:
        type: string
      balance:
        type: string
      transactionType:
        type: string
      category:
        type: string
  InformationEdit:
    type: object
    properties:
      description:
        type: string
      type:
        type: string
      category:
        type: string
  TansactionAddNote:
    type: object
    properties:
      content:
        type: string
  TransactionNote:
    type: object
    properties:
      content:
        type: string
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
  BalanceResponse:
    type: object
    properties:
      body:
        type: object
        properties:
          id:
            type: integer
          date:
            type: string
          description:
            type: string
          mount:
            type: string
          balance:
            type: string
          transactionType:
            type: string
          category:
            type: string
          notes:
            type: array
            items:
              type: object
              properties:
                id:
                  type: integer
                content:
                  type: string
  TransactionDetailResponse:
    type: object
    properties:
      id:
        type: number
      date:
        type: string
      description:
        type: string
      mount:
        type: string
      balance:
        type: string
      transactionType:
        type: string
      category:
        type: string
      notes:
        type: array
        items:
          type: object
          properties:
            id:
              type: integer
            content:
              type: string
  CategoryEditResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
  TransactionNoteReponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string

    